import api from './api';
const studentService = {
  getSubscription: () => api.get('/subscriptions/me'),
  createSubscription: (data) => api.post('/subscriptions', data),
  activateWithPin: (data) => api.post('/subscriptions/activate-with-pin', data),
  activateWithBalance: () => api.post('/subscriptions/activate-with-balance'),
  activateByUpline: (data) => api.post('/subscriptions/activate-by-upline', data),
  requestWithdrawal: (data) => api.post('/withdrawals', data),
  sendWithdrawalOTP: () => api.post('/withdrawals/send-otp'),
  getWithdrawalFeeInfo: () => api.get('/withdrawals/fee-info'),
  getMyWithdrawals: (params) => api.get('/withdrawals', { params }),
  getMyCertificates: () => api.get('/certificates'),
  getAnnouncements: (params) => api.get('/announcements', { params }),
  getTickets: (params) => api.get('/support', { params }),
  createTicket: (data) => api.post('/support', data),
  getTicket: (id) => api.get(`/support/${id}`),
  addMessage: (id, data) => api.post(`/support/${id}/messages`, data),
  getCopyStats: () => api.get('/copy-trading/stats'),
  getCopyHistory: (params) => api.get('/copy-trading/history', { params }),
  getRanks: () => api.get('/ranks'),
  getMyRank: () => api.get('/ranks/me'),
  connectMT: (data) => api.post('/users/connect-mt', data),
  disconnectMT: () => api.delete('/users/disconnect-mt'),
  markWhatsappClick: () => api.post('/users/whatsapp-click'),
  getSettings: () => api.get('/settings/public'),
  getMyPurchases: (params) => api.get('/course-purchases/my', { params }),
  createPurchase: (data) => api.post('/course-purchases', data),
  getApprovalStatus: () => api.get('/course-purchases/my/approval-status'),
  createPaymentIntent: (data) => api.post('/payments/create-payment-intent', data),
  getBrokers: () => api.get('/brokers'),
  getStudentDashboard: () => api.get('/users/student/dashboard'),
};
export default studentService;
